### PR TITLE
fix: revertPattern in angular preset should also match regular revert…

### PR DESCRIPTION
**Pull request by YuraBeznos**
… format

Part of conventional-changelog/issues/348

### CODE REVIEW

**Comment by tommywo** [comment]
Hi @YuraBeznos. Thank you for contributing. 🎉  
Can you add a unit test for that?

**Comment by stevemao** [comment]
Should conventional-changelog-conventionalcommits use the default revert message and leave the angular preset as is?

**Comment by tommywo** [comment]
@stevemao https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#revert now doesn't say the message format is autogenerated, but it uses word SHOULD not MUST, so I personally think default message format should be also parsed in angular preset.

**Comment by tommywo** [comment]
@bcoe, @jbottigliero, @byCedric  what's your opinion on this? this might affect how commitlint is working after https://github.com/conventional-changelog/commitlint/pull/821 is merged

**Comment by bcoe** [comment]
should we just make the regex case-insensitive? thoughts @tommywo?

**Comment by byCedric** [comment]
@tommywo I don't think this is an issue in Commitlint, it's backwards compatible 😄 (at least, I think it is?) We also keep track of some "ignored commits", like reverts ([which is case-insensitive already](https://github.com/conventional-changelog/commitlint/blob/master/%40commitlint/is-ignored/src/defaults.ts#L22))

**Comment by tommywo** [comment]
closing in favor of #545

**Pull request closed without merging**
