### PR TITLE
feat(parser): parse merge message and conventional commit on same line

### PR DESCRIPTION
**Pull request by cgosiak**
Can now parse both a merge message and a conventional commit that appear on the same line

### CODE REVIEW

**Comment by stevemao** [comment]
Hi @cgosiak , thanks for the PR. If you want to generate a changelog based on pull-request messages, you could have a look at how [ember](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-ember) does it. Let me know if that solves your problem.

**Comment by cgosiak** [comment]
So ember seems to do something closer to what I am looking for. However, the changes that I propose would make it so the "Merge Pattern" and a Conventional Commit may reside on the same line. I know that this is the case for what I am dealing with now; but it seems like it could be a generic enough enhancement that other variations may find value in it.

**Comment by cgosiak** [comment]
@stevemao any thoughts?

**Comment by bcoe** [comment]
@cgosiak I'm not a fan of this being in the base library; if you want to handle the edge case of commits rewritten with a `Merge ` in the commit line, perhaps create your own preset?

**Comment by bcoe** [comment]
@cgosiak please feel free to start a conversation here:

http://devtoolscommunity.herokuapp.com/

I think this could potentially be a candidate for writing your own preset.

**Pull request closed without merging**
