### PR TITLE
feat(cli): Support specifing commit-ish to generate changelog from

### PR DESCRIPTION
**Pull request by briandipalma**
closes: #189

### CODE REVIEW

**Comment by stevemao** [comment]
https://github.com/conventional-changelog/conventional-changelog/issues/195 should be a more generic solution.

**Comment by briandipalma** [comment]
Hi @stevemao thanks for the reply. I'm not sure what the plan is with the rc file, there is a config file option but it seems underpowered. If a config file is supported why not allow it to configure everything e.g. preset, input/output, release-count, same-file etc? Currently the config file allows us to configure `from` and `path` of the git options but the other options have to be specified on the CLI.

The only option that's missing from the CLI for us is `from`. We are using the CLI in a monorepo with ~20 packages (https://github.com/caplin/caplin-dev-tools) so tagging the repo doesn't work as packages all have different versions. Tagging Lerna style might help but our repo structure is different. I'll give that a shot as we release packages and see if that helps us.

**Comment by RomanMinkin** [comment]
@stevemao is there a way this PR can make it in since #195 is still in development? This one looks like a simple and elegant solution similar to `--release-count`.

**Comment by briandipalma** [comment]
Happy to reopen if someone wants.

**Comment by stevemao** [comment]
The problem with this PR is `from` is an option of `gitRawCommitsOpts`, not a conventional-changelog's `config`. Therefore, you'd add all options from the dependencies to the cli. 

If anyone want to create a PR to fix #195 that'd be great.

**Comment by briandipalma** [comment]
I could change it to `from-sha` so it isn't the same?

**Comment by RomanMinkin** [comment]
That's the beauty of `conventional-changelog-cli`, I just drop it into Makefile and forget, no config, no extra files.

In my case all I wanted is to strip all pre `1.0.0` text out of `CHANGELOG.md`. 
My current solution is to run [replace](https://www.npmjs.com/package/replace) right after the change log generation:
```bash
replace --silent '^(\#\s\[1\.0\.0\].+)([^]+)' '$1' CHANGELOG.md
```

**Comment by stevemao** [comment]
If we want to add extra options in conventional-changelog, we should add it to conventional-changelog (or core), cli is just a proxy for the interface.

> That's the beauty of `conventional-changelog-cli`, I just drop it into Makefile and forget, no config, no extra files.

I believe that flags the same as config, or extra files. When it's small flags are nice. When it's big it becomes unmaintainable and better to put in extra files.

Most config in conventional-changelog should be either not a part of the submodules (context, gitRawCommitsOpts, parserOpts, writerOpts) to avoid duplicates, or to help coordinate across different submodules that are hard to config individually (`releaseCount` is a good example).

**Pull request closed without merging**
