### PR TITLE
feat(conventional-commits-parser): add flag to enable/disable multiple-scopes (default: enabled)

### PR DESCRIPTION
**Pull request by wlc015f**
This PR close to [issue 4015](https://github.com/conventional-changelog/commitlint/issues/4015)

migrate separating scopes logic code from `@commitlint/rules/src/scope-enum.ts`.

to Implement the feature add `isEnableMultipleScopes` and `scopeDelimitersPattern` parserOptions:

 - `isEnableMultipleScopes` used to determine whether to separate scopes by slash or comma delimiters contain in scope.

 - `scopeDelimitersPattern` used to separate scopes if `isEnableMultipleScopes` value is true.

the two default parserOptions values of two parserOptions refer to [@commitlint/rules/src/scope-enum.ts](https://github.com/conventional-changelog/commitlint/blob/aa4df36b1d07e56230ff569aec5af727f1144aae/%40commitlint/rules/src/scope-enum.ts#L16), this pr make it configurable, and work as before if not config

### CODE REVIEW

**Comment by knocte** [comment]
Why do we need a flag at all? Why not just assume multiple scopes? Do we have a unit test that would fail if this is done without a flag?

**Comment by wlc015f** [comment]
> Why do we need a flag at all? Why not just assume multiple scopes? Do we have a unit test that would fail if this is done without a flag?

our projects previous use scope like: `feat(A/B): commit msg`, B is a sub scope of A, when we update `@commitlint/cli` from 8.3.5 to 19.2.1, it doesn't work well as before, because for version 19.2.1 "/" is scopes delimiter to separate input scope string into several scopes.  `scopeEnum` function in  `@commitlint/rules` would separate input scope "A/B" to scope "A" and "B", scope "A/B" can not pass scopeEnum check.

so i want to migrate separating scopes logic code from `@commitlint/rules/src/scope-enum.ts` to  package`conventional-commits-parser`, set default behavior work as before in `@commitlint/rules`, and then set `isEnableMultipleScopes`=false can solve my problem.

**Comment by knocte** [comment]
Why was this closed?

**Comment by wlc015f** [comment]
> Why was this closed?

this feature is a fix for a very old version. Waiting for the next+2 roadmap update there might bring better planning and implementation.

**Pull request closed without merging**
