### PR TITLE
feat!: cleanup presets interface

### PR DESCRIPTION
**Pull request by dangreen**
BREAKING CHANGES: now preset object provides `commits`, `parser`, `writer` and `whatBump` properties.

### CODE REVIEW

**Comment by knocte** [comment]
@dangreen I'm just curious, when do you plan to release a new version with this breaking change?

**Comment by dangreen** [comment]
@knocte We have [milestone for next release](https://github.com/conventional-changelog/conventional-changelog/milestone/4), but I can't name a date, because it depends on my free time.

**Comment by knocte** [comment]
> but I can't name a date, because it depends on my free time.

I'm of course not asking for it to be earlier rather than later. If anything, it would be the other way around; because I'm trying to understand why the last version of this pkg was released so long ago: https://www.npmjs.com/package/conventional-commits-parser?activeTab=versions

**Comment by dangreen** [comment]
@knocte Because there are packages that depends on conventional-commits-parser that also should be updated. So I have plan to publish all updated packages at once.

**Pull request merged**
