### PR TITLE
feat: migrate core conventional-changelog packages to lerna

### PR DESCRIPTION
**Pull request by bcoe**
## Problem

* it's difficult for new users to sift through all of the similarly named conventional-changelog repos, to find one of the modules they're most likely to need (conventional-changelog-cli, standard-version, etc).
* when adding a new feature (in my case I'd like to [add lerna support](https://github.com/conventional-changelog/standard-version/issues/156) to standard-version) changes are required across many modules, making work slow.

## Proposed Solution

[Lerna](https://github.com/lerna) is a tool developed by the babel team for managing mono-repos. By pulling the core conventional-changelog libraries into a mono-repo using Lerna:

* It's still easy to release modules independently (note that I enabled [independent mode](https://github.com/lerna/lerna#independent-mode---independent)).
* it makes it easier to add features to conventional-changelog (I'd _love_ to have per-package CHANGELOG generation for lerna-style repos).
* it gives us a centralized repo to engage in discussion on (`conventional-changelog/conventional-changelog`).
* it allows us to better draw our users' attention to the important repos (hiding utility repos).

### CODE REVIEW

**Comment by stevemao** [comment]
My first impression is... its amazing. You even kept all the git history. Great work @bcoe :)

**Comment by datitisev** [comment]
@stevemao There's a package called [Commitizen](http://commitizen.github.io/cz-cli/) that offers an interactive CLI to generate commit messages.

**Comment by bcoe** [comment]
@stevemao @datitisev the newest version of lerna has an `import` command that lets you pluck a project in with history; quite slick 👍 

As soon as we get this landed, the first feature I plan on working on is getting per-package CHANGELOG generation working -- which I want for Istanbul too (I've been in the process of [moving this to lerna](https://github.com/istanbuljs/istanbuljs)).

**Comment by bcoe** [comment]
@stevemao when you have two secs; mind making sure myself and @Tapppi are added as owners on each of the npm modules added to the `/packages` folder? Otherwise the first release via lerna will be hard 👍

**Pull request merged**
