### PR TITLE
fix(tags-parsing): update command to get tags

### PR DESCRIPTION
**Pull request by blowsie**
refs #164

### CODE REVIEW

**Comment by stevemao** [comment]
@blowsie tests failed

**Comment by blowsie** [comment]
I think the tests just failed due to indentation. What would you suggest I do?

**Comment by stevemao** [comment]
fix the tests. You can click on the links here. They should also fail on your local machine.

**Comment by stevemao** [comment]
Also there's no new tests added to the PR. What exactly does this PR fix?

**Comment by blowsie** [comment]
Gitlabs

**Pull request closed without merging**
