### PR TITLE
fix: find package.json from cwd upwards

### PR DESCRIPTION
**Pull request by marionebl**
* smarten up logic to find a "root" package json a bit
* use pkg-up to find "root"
* use load-json-file for nice error messages
* move module scope procedure to getPkg
* handle missing package.json without logged warning
* propagate possible json errors

### CODE REVIEW

**Comment by stevemao** [comment]
Thanks for the PR! Could you use [`read-pkg-up`](https://www.npmjs.com/package/read-pkg-up)?

**Comment by stevemao** [comment]
Also the commit message should probably be:
`feat(angular): find package.json from cwd upwards`

**Comment by marionebl** [comment]
Sure, adapted the changes according to your suggestions.

**Comment by marionebl** [comment]
Could you retrigger https://ci.appveyor.com/project/stevemao/conventional-changelog/build/1.0.126? npm seems to have acted up on this build.

**Pull request merged**
