### PR TITLE
feat(recommended-bump): add `eslint` preset

### PR DESCRIPTION
**Pull request by garyyeap**
As title, add eslint preset supports

### CODE REVIEW

**Comment by hbetts** [comment]
As I [commented here](https://github.com/conventional-changelog-archived-repos/conventional-recommended-bump/pull/23#issuecomment-339361967), I'm fine with accepting this change until #195 has been completed.

**Comment by hbetts** [comment]
👍 looks good to me!

@stevemao?

**Comment by stevemao** [comment]
Like I said, I'm not sure if anyone is using `preset` and I'm more towards user land `config` files.

**Comment by garyyeap** [comment]
Thanks @hbetts, now I noticed the discussion on #195.
Since the content of `preset`(or `config`) for `recommended-bump` is totally different from `conventional-changelog` even is the same convention, I would like to propose an idea that we separate out `recommended-bump`'s presets like `conventional-changelog` does:

change the `require` action from

> config = require('./presets/' + options.preset);

to 

> options.config = require('conventional-recommended-bump-' + options.preset.toLowerCase());

as `conventional-changelog` does

> options.config = require('conventional-changelog-' + options.preset.toLowerCase());

Then I will close & change this PR to a third party package.

This may making more backward-compatibility when the final result of `rc` file discussion come out.

**Comment by stevemao** [comment]
Yeah, they are configs for different projects. But the idea is the same. We should remove presets and do #195

Let's merge this first then we'll do #195 later :)

**Comment by hbetts** [comment]
As a side note @stevemao and @garyyeap I kind of wonder if we can merge the two configurations together - #241

**Comment by stevemao** [comment]
@hbetts That would be good. I also mentioned that if we could share config with tools like `commitizen` and `commitlint`.

**Comment by garyyeap** [comment]
@hbetts First we have to catch up all existing `changelog` conventions for `recommended-bump`.
I think I can help with that and I'm wondering `conventional-changelog-*` presets still accepting PR?

**Comment by hbetts** [comment]
@stevemao @garyyeap, if you don't mind, let's move our discussion to #241 😄

**Pull request merged**
