### PR TITLE
Reuse parserOpts in conventional-recommended-bump

### PR DESCRIPTION
**Pull request by bertho-zero**

### CODE REVIEW

**Comment by damianopetrungaro** [comment]
Hey @bertho-zero thank you for the PR!

Could you please write commits as the specs propose?

**Comment by bertho-zero** [comment]
I noticed that the value of the parserOpts key was the same as the parserOpts.js file, so it is less repetitive to reuse it.

**Comment by hbetts** [comment]
Thank you @bertho-zero for putting together this pull request. It was a cleanup step that was planned in #241, but I'm glad to see someone jumping in and fixing it now.

As noted by @damianopetrungaro, can you please update your commit messages to conform to our commit convention? At that point we should be able to accept this pull request.

**Comment by hbetts** [comment]
I accepted pull request #335, which applies a similar change to all presets.

Successfully published:

    conventional-changelog-angular@5.0.0
    conventional-changelog-atom@2.0.0
    conventional-changelog-cli@2.0.1
    conventional-changelog-codemirror@2.0.0
    conventional-changelog-ember@2.0.0
    conventional-changelog-eslint@3.0.0
    conventional-changelog-express@2.0.0
    conventional-changelog-jquery@3.0.0
    conventional-changelog-jshint@2.0.0
    conventional-changelog@2.0.1
    conventional-recommended-bump@4.0.0
    gulp-conventional-changelog@2.0.1

**Pull request closed without merging**
