### PR TITLE
Remove anchor from header templates

### LINKED ISSUE #186: link Name
Hi,

It's more a question than an issue.
I'm using CLI and in the top of my changelog.md I've got this:

`<a name=""></a>`

What is it for? Is it possible to not write this line?

Thanks

### PR DESCRIPTION
**Pull request by TheDancingCode**
Closes #186.

### CODE REVIEW

**Comment by hbetts** [comment]
@TheDancingCode your changes look good :+1: 

Would you please update your commit message to be something like `refactor: remove anchor from header templates` so that it matches [our commit convention](https://conventionalcommits.org/)? (Makes our release tooling _Just Work_)

**Comment by TheDancingCode** [comment]
Done.

**Comment by hbetts** [comment]
:+1: Looks good to me.

**Comment by hbetts** [comment]
Successfully published:
 - conventional-changelog-angular@3.0.3
 - conventional-changelog-atom@0.2.6
 - conventional-changelog-cli@1.3.18
 - conventional-changelog-codemirror@0.3.6
 - conventional-changelog-core@2.0.7
 - conventional-changelog-ember@0.3.8
 - conventional-changelog-eslint@1.0.7
 - conventional-changelog-jquery@1.3.6
 - conventional-changelog-jshint@0.3.6
 - conventional-changelog-writer@3.0.6
 - conventional-changelog@1.1.20
 - gulp-conventional-changelog@1.1.20
 - standard-changelog@1.0.15

**Comment by pvdlg** [comment]
Why removing the anchor?

The anchor was really useful to create a link to a GitHub release and scroll the page to a specific release. For example: https://github.com/semantic-release/semantic-release/releases#15.1.3

**Comment by stevemao** [comment]
This needs to be a breaking change coz several downstream wrappers (incorrectly) rely on it...

**Comment by hbetts** [comment]
@stevemao I'll revert the commit, release patches, and then cherry-pick the commit with a modified message to make the release a breaking change.

@pvdlg since this change has technically "gone out", can you please file an issue requesting we keep the feature, along with your example. That would really help us to better understand our user's use cases.

**Comment by TheDancingCode** [comment]
Alright.

**Pull request merged**
